version: "3.8"
services:
  # mongo
  godkoz-db:
    image: mongo:latest
    container_name: godkoz-db
    restart: always
    volumes:
      - ./godkoz-db:/data/db
    networks:
      - database

  # backend
  godkoz-service:
    build: ./server/godkoz-api
    container_name: godkoz-api
    restart: always
    environment:
      - VIRTUAL_HOST=eiei-api-dev.chayaninrojarat.dev
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=eiei-api-dev.chayaninrojarat.dev
    networks:
      - proxy
      - database

  # frontend
  godkoz-web-app:
    build: ./client/app
    container_name: web-app
    restart: always
    environment:
      - VIRTUAL_HOST=eiei-web-dev.chayaninrojarat.dev
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=eiei-web-dev.chayaninrojarat.dev
    networks:
      - proxy

networks:
  proxy:
    external:
      name: reverse-proxy
  database:
